# This workflow is triggered by a self-service action in Port to create a new repository.
name: Scaffold New Service

# This allows the workflow to be triggered manually or by an API call.
on:
  workflow_dispatch:
    # Define the inputs that the workflow expects to receive from Port.
    inputs:
      repo_name:
        description: 'Name for the new repository'
        required: true
        type: string

jobs:
  scaffold:
    runs-on: ubuntu-latest
    # Define environment variables at the job level to make them accessible to all steps.
    env:
      REPO_NAME: ${{ github.event.inputs.repo_name }}
      ORG_NAME: "tim-gowan" # Your GitHub username or organization
    steps:
      - name: Create repository from template
        env:
          # A GitHub Personal Access Token (PAT) with 'repo' scope is required.
          # The default GITHUB_TOKEN does not have permission to create repositories.
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
          TEMPLATE_REPO: "tim-gowan/templates-and-workflows"
        run: |
          # Use the GitHub CLI to create a new repository from the template.
          echo "Creating repository: ${{ env.ORG_NAME }}/${{ env.REPO_NAME }}"
          gh repo create ${{ env.ORG_NAME }}/${{ env.REPO_NAME }} --template=${{ env.TEMPLATE_REPO }} --public --description="New service: ${{ env.REPO_NAME }}"
          echo "✅ Repository ${{ env.ORG_NAME }}/${{ env.REPO_NAME }} created successfully!"

      # This step will register the newly created repo as a microservice entity in Port.
      - name: Register new service in Port 🚢
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: UPSERT
          blueprint: 'microservice'
          identifier: '"${{ env.ORG_NAME }}/${{ env.REPO_NAME }}"'
          title: '"${{ env.REPO_NAME }}"'
          properties: |
            {
              "url": "https://github.com/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}"
            }

      - name: All done! ✅
        if: success()
        run: |
          echo "🎉 Scaffold successful!"
          echo "Access your new repository here: https://github.com/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}"
