# This workflow is triggered by a self-service action in Port to create a new repository.
name: Scaffold New Service

# This allows the workflow to be triggered manually or by an API call.
on:
  workflow_dispatch:
    # Define the inputs that the workflow expects to receive from Port.
    inputs:
      repo_name:
        description: 'Name for the new repository'
        required: true
        type: string
      port_run_id:
        description: 'The Port run ID for reporting'
        required: true
        type: string

jobs:
  scaffold:
    runs-on: ubuntu-latest
    # Define environment variables at the job level.
    env:
      REPO_NAME: ${{ github.event.inputs.repo_name }}
      ORG_NAME: "tim-gowan" # Your GitHub username or organization
      PORT_RUN_ID: ${{ github.event.inputs.port_run_id }}
      PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
      PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}

    steps:
      - name: Send Starting Message to Port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ env.PORT_CLIENT_ID }}
          clientSecret: ${{ env.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ env.PORT_RUN_ID }}
          logMessage: "🚀 Starting scaffold process for repository: ${{ env.REPO_NAME }}"

      - name: Create repository from template
        id: create_repo
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
          TEMPLATE_REPO: "tim-gowan/templates-and-workflows"
        run: |
          # Use the GitHub CLI to create a new repository from the template.
          # Capture stderr to check for specific errors and continue on error.
          echo "Creating repository: ${{ env.ORG_NAME }}/${{ env.REPO_NAME }}"
          gh repo create ${{ env.ORG_NAME }}/${{ env.REPO_NAME }} --template=${{ env.TEMPLATE_REPO }} --public --description
